server:
  port: 9090
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/skywalking?useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      connection-test-query: SELECT 1
      max-lifetime: 30000
mybatis:
  type-aliases-package: com.yisquare.springboot.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
## 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
## shiro配置
shiro:
  web:
    enabled: true
  loginUrl: /login
springfox:
  documentation:
    swagger-ui:
      enabled=true:
